<?xml version="1.0"?>
<robot name="real_differential_robot" xmlns:xacro="http://www.ros.org/wiki/xacro">

  <material name="blue"><color rgba="0.0 0.0 0.8 1.0"/></material>
  <material name="black"><color rgba="0.0 0.0 0.0 1.0"/></material>
  <material name="white"><color rgba="1.0 1.0 1.0 1.0"/></material>
  <material name="green"><color rgba="0.0 0.8 0.0 1.0"/></material>
  <material name="red"><color rgba="0.8 0.0 0.0 1.0"/></material>
  <material name="gray"><color rgba="0.5 0.5 0.5 1.0"/></material>

  <xacro:property name="wheel_radius" value="0.103" />         <xacro:property name="wheel_width" value="0.08" />             <xacro:property name="wheel_base" value="0.503" />             <xacro:property name="base_width" value="0.45" />             <xacro:property name="base_length" value="0.60" />             <xacro:property name="base_height" value="0.27" />             <xacro:property name="wheel_forward_offset" value="0.30" /> <xacro:property name="base_ground_clearance" value="0.103" /> <xacro:property name="camera_height_offset" value="0.0125" /> <xacro:property name="camera_tilt_angle" value="0.25" />       <link name="world"/>

  <link name="base_link">
    <visual>
      <origin xyz="0 0 ${base_ground_clearance + base_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="gray"/>
    </visual>
    <collision>
      <origin xyz="0 0 ${base_ground_clearance + base_height/2}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>
  </link>

  <joint name="world_to_base_joint" type="fixed">
    <parent link="world"/>
    <child link="base_link"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <link name="left_wheel_link">
    <visual>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <visual>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius * 0.6}" length="${wheel_width + 0.01}"/>
      </geometry>
      <material name="gray"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
  </link>

  <joint name="left_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="left_wheel_link"/>
    <origin xyz="${wheel_forward_offset} ${wheel_base/2} ${wheel_radius}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.1" friction="0.1"/>
  </joint>

  <link name="right_wheel_link">
    <visual>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
      <material name="black"/>
    </visual>
    <visual>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius * 0.6}" length="${wheel_width + 0.01}"/>
      </geometry>
      <material name="gray"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="1.5708 0 0"/>
      <geometry>
        <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
      </geometry>
    </collision>
  </link>

  <joint name="right_wheel_joint" type="continuous">
    <parent link="base_link"/>
    <child link="right_wheel_link"/>
    <origin xyz="${wheel_forward_offset} ${-wheel_base/2} ${wheel_radius}" rpy="0 0 0"/>
    <axis xyz="0 1 0"/>
    <dynamics damping="0.1" friction="0.1"/>
  </joint>

  <link name="rear_left_caster_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="0.05"/>
      </geometry>
      <material name="white"/>
    </visual>
    <visual>
      <origin xyz="0 0 0.06" rpy="0 0 0"/>
      <geometry>
        <box size="0.05 0.08 0.02"/>
      </geometry>
      <material name="gray"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="0.05"/>
      </geometry>
    </collision>
  </link>

  <joint name="rear_left_caster_joint" type="fixed">
    <parent link="base_link"/>
    <child link="rear_left_caster_link"/>
    <origin xyz="-0.25 0.2 0.045" rpy="0 0 0"/>
  </joint>

  <link name="rear_right_caster_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="0.05"/>
      </geometry>
      <material name="white"/>
    </visual>
    <visual>
      <origin xyz="0 0 0.06" rpy="0 0 0"/>
      <geometry>
        <box size="0.05 0.08 0.02"/>
      </geometry>
      <material name="gray"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <sphere radius="0.05"/>
      </geometry>
    </collision>
  </link>

  <joint name="rear_right_caster_joint" type="fixed">
    <parent link="base_link"/>
    <child link="rear_right_caster_link"/>
    <origin xyz="-0.25 -0.2 0.045" rpy="0 0 0"/>
  </joint>

  <link name="camera_link">
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.025 0.09 0.025"/>
      </geometry>
      <material name="black"/>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="0.025 0.09 0.025"/>
      </geometry>
    </collision>
  </link>

  <joint name="camera_joint" type="fixed">
    <parent link="base_link"/>
    <child link="camera_link"/>
    <origin xyz="${wheel_forward_offset} 0.0 ${base_ground_clearance + base_height + camera_height_offset}" rpy="0 ${camera_tilt_angle} 0"/>
  </joint>

  <link name="camera_color_frame"/>
  <joint name="camera_color_joint" type="fixed">
    <parent link="camera_link"/>
    <child link="camera_color_frame"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <link name="camera_color_optical_frame"/>
  <joint name="camera_color_optical_joint" type="fixed">
    <parent link="camera_color_frame"/>
    <child link="camera_color_optical_frame"/>
    <origin xyz="0 0 0" rpy="-1.5708 0 -1.5708"/>
     </joint>

</robot>