slam_toolbox:
  ros__parameters:
    odom_frame: "odom"
    map_frame: "map"
    base_frame: "base_link"
    scan_topic: "/scan"
    mode: "mapping"  # mapping 또는 localization
    transform_publish_period: 0.02
    map_update_interval: 5.0
    resolution: 0.05
    max_laser_range: 3.0
    minimum_travel_distance: 0.5
    minimum_travel_heading: 0.5
    do_loop_closing: true
    loop_search_maximum_distance: 3.0